### ISSUE TITLE
Exposer le .tex utilisé par pdflatex

### ISSUE THREAD

**Issue by hugoroy** [Sniperovitch/cocktail#10]
Cocktail garde le pdf, mais pas le .tex. il faudrait garder le .tex accessible aussi :-)

**Comment by Sniperovitch** [comment]
Résolu dans [Issue #10 (hugoroy) Exposer le .tex utilisé par pdflatex](https://github.com/Sniperovitch/cocktail/commit/74aa1e791304a845ccf51367be9cc2718cbf9f9e)

**Comment by hugoroy** [comment]
↪ David Sniperovitch / avril 13, 2017 16:18:
> Résolu dans [Issue #10 (hugoroy) Exposer le .tex utilisé par pdflatex](https://github.com/Sniperovitch/cocktail/commit/74aa1e791304a845ccf51367be9cc2718cbf9f9e)

OK! Je peux faire le git pull?
